name: ml_linalg
description: SIMD-based linear algebra and statistics, efficient manipulation with numeric data
version: 13.12.7
homepage: https://github.com/gyrdym/ml_linalg

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  quiver: ^3.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^2.4.2
  build_test: ^2.1.7
  mockito: ^5.0.0
  path: ^1.8.0
  pedantic: ^1.11.0
  test: ^1.16.0
